FROM node:lts

WORKDIR /app
COPY package*.json ./
RUN npm install -g ts-node typescript && \
    npm install --include=dev && \
    npm cache clean --force

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]