version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - auth-service
      - user-service
      - content-service

  frontend:
    build: ./frontend
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  auth-service:
    build: ./auth-service
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  user-service:
    build: ./user-service
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production

  content-service:
    build: ./content-service
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
