version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - auth-service
      - user-service
      - content-service

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"

  auth-service:
    build: ./auth-service
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "4000:4000"

  user-service:
    build: ./user-service
    volumes:
      - ./user-service:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "4001:4001"

  content-service:
    build: ./content-service
    volumes:
      - ./content-service:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "4002:4002"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
